eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
micorservices:
  orderservice:
    endpoints:
      bookorder:
        url: http://ORDER-SERVICE/order/bookorder
  paymentservice:
    endpoints:
      dopayment:
        url: http://PAYMENT-SERVICE/payment/dopayment
